const GET_BALANCE_LOADING = "GET_BALANCE_LOADING";
const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
const GET_BALANCE_ERROR = "GET_BALANCE_ERROR";

export default { GET_BALANCE_LOADING, GET_BALANCE_SUCCESS, GET_BALANCE_ERROR };
