const GET_CRYPTOS_LOADING = "GET_CRYPTOS_LOADING";
const GET_CRYPTOS_SUCCESS = "GET_CRYPTOS_SUCCESS";
const GET_CRYPTOS_ERROR = "GET_CRYPTOS_ERROR";

export default { GET_CRYPTOS_LOADING, GET_CRYPTOS_SUCCESS, GET_CRYPTOS_ERROR };
